### ISSUE TITLE
Yay!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-constanza-sosa#1]
Buen trabajo @constanza-sosa  !

Algunas pistas para mejorarlo:

- [x] Añades datos al estado pero no lo usas. Hay que usarlo.
- [x] `<Fragment>` lo usamos cuando queremos agrupar varios elementos o componentes sin generar un contenedor extra, si ya todo está metido en un `<div>`, como en el caso de la card, no necesitamos este Fragment.
- [x] Revisa los metadatos en index.html (lang, title...)

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by constanza-sosa** [comment]
Hecho lo necesario! Te he mandado pull request! Para la evaluación final intentaré hacer los otros :D

**Comment by oneeyedman** [comment]
Bien, pero hay que indentar ese código.
